version: "2"

services:
    app:
        build:
            context: .
            dockerfile: dev.dockerfile
        depends_on:
            - db
        volumes:
            - .:/app
            - /app/app/cache
            - /app/app/sessions

    db:
        image: mysql:5.6
        environment:
            MYSQL_ROOT_PASSWORD: akeneo_pim
            MYSQL_DATABASE: akeneo_pim
            MYSQL_USER: akeneo_pim
            MYSQL_PASSWORD: akeneo_pim
