services:
    Akeneo\Connectivity\Connection\Infrastructure\Cli\UpdateAuditDataCommand:
        class: Akeneo\Connectivity\Connection\Infrastructure\Cli\UpdateAuditDataCommand
        arguments:
            - '@akeneo_connectivity.connection.application.audit.handler.update_product_event_count'
            - '@akeneo_connectivity_connection.persistence.query.select_event_dates_to_refresh'
        tags:
            - { name: 'console.command' }

    Akeneo\Connectivity\Connection\Infrastructure\Cli\CreateConnectionCommand:
        class: Akeneo\Connectivity\Connection\Infrastructure\Cli\CreateConnectionCommand
        arguments:
            - '@akeneo_connectivity.connection.application.handler.create_connection'
        tags:
            - { name: 'console.command' }

    Akeneo\Connectivity\Connection\Infrastructure\Cli\PurgeReadProductTableCommand:
        class: Akeneo\Connectivity\Connection\Infrastructure\Cli\PurgeReadProductTableCommand
        arguments:
            - '@akeneo_connectivity_connection.persistence.query.purge_read_product'
        tags:
            - { name: 'console.command' }
