imports:
    - { resource: ../../../tests/back/Acceptance/Resources/config/pim/repositories.yml }
    - { resource: ../../../tests/back/Acceptance/Resources/config/pim/queries.yml }
    - { resource: ../../../tests/back/Acceptance/Resources/config/pim/file_storage.yml }
    - { resource: ../../../tests/back/Platform/Acceptance/CatalogVolumeMonitoring/Resources/config/pim/queries.yml }
    - { resource: ../../../tests/back/Acceptance/Resources/config/behat/services.yml }
    - { resource: ../../../tests/back/Platform/Acceptance/CatalogVolumeMonitoring/Resources/config/behat/services.yml }
    - { resource: ../../../tests/back/Pim/Enrichment/Acceptance/Resources/config/behat/services.yml }
    - { resource: ../../../tests/back/Platform/Acceptance/Analytics/Resources/config/queries.yml }
    # Akeneo/Connectivity/Connection
    - { resource: ../../../src/Akeneo/Connectivity/Connection/back/tests/Acceptance/Resources/config/queries.yml }
    - { resource: ../../../src/Akeneo/Connectivity/Connection/back/tests/Acceptance/Resources/config/repositories.yml }
    - { resource: ../../../src/Akeneo/Connectivity/Connection/back/tests/Acceptance/Resources/config/services.yml }

services:
    akeneo_integration_tests.doctrine.connection.connection_closer:
        class: Akeneo\Test\IntegrationTestsBundle\Doctrine\Connection\ConnectionCloser
        arguments:
            - '@doctrine'
